<template>
  <div class="container mt-3">
    <div class="row">
      <div class="col">
        <h3>Pending Sales</h3>
        <hr />
        <PendingSale
          v-for="sale in pendingSaleList"
          :key="sale.id"
          :sale-id="sale.saleId"
          :customer-name="'mario sebastian'"
          :paid="sale.fullyPaid"
          @selectSale="selectSale"
        />
      </div>
      <div class="col mt-5">
        <PendingSaleDetails
          :pendingSale="selectedSale"
          @resetSelectedSale="resetSelectedSale"
        />
      </div>
    </div>
  </div>
</template>

<script>
// @ is an alias to /src
import PendingSale from "@/components/PendingSale.vue";
import PendingSaleDetails from "../components/PendingSaleDetails.vue";
import _ from "lodash";

// import axios from "axios";

export default {
  name: "Home",
  data: () => {
    return {
      selectedSale: null,
      pendingSaleList: [
        {
          saleId: 1,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T16:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: true,
        },
        {
          saleId: 2,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T16:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 3,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T16:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 4,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T16:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 5,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T16:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 6,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T16:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 7,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T16:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 8,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T16:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 9,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T16:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 10,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T16:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 11,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T16:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 12,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 13,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 14,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 15,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 16,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 17,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 18,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 19,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 20,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 21,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 22,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 23,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 24,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 25,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 26,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 27,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 28,
          promotionId: 2,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 29,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 2.8282828111e7,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 30,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 100.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 31,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 32,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 33,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 34,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 35,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 36,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 37,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 38,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 100.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 39,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 40,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.11,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: false,
        },
        {
          saleId: 41,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T07:11:11",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.111,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: true,
        },
        {
          saleId: 42,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T11:59:00",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.111,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: true,
        },
        {
          saleId: 43,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T12:00:00",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.111,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: true,
        },
        {
          saleId: 44,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T13:00:00",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.111,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: true,
        },
        {
          saleId: 45,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T13:00:00",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.111,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: true,
        },
        {
          saleId: 46,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T12:00:00",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.111,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: true,
        },
        {
          saleId: 47,
          promotionId: 0,
          employeeId: 1,
          storeId: 1,
          grandTotal: 111.111,
          pickupDate: null,
          initialDepositDate: "2020-12-22T13:00:00",
          initialDepositType: "Debit: BCA",
          initialDepositAmount: 111.111,
          finalDepositDate: null,
          finalDepositType: null,
          finalDepositAmount: 0.0,
          fullyPaid: true,
        },
      ],
    };
  },
  components: {
    PendingSale,
    PendingSaleDetails,
  },
  created() {
    // axios
    //   .get("http://192.168.1.106:8080/posEndpoint/getPendingSaleList?storeId=1")
    //   .then((response) => {
    //     this.pendingSaleList = [...response.data];
    //   })
    //   .catch((err) => console.log(err));
  },
  methods: {
    selectSale(saleId) {
      this.selectedSale = _.find(
        this.pendingSaleList,
        (x) => x.saleId === saleId
      );
    },
    resetSelectedSale() {
      this.selectedSale = null;
    },
  },
};
</script>
